package br.com.fiap.bibliothecca_api.model.Enums;

public enum Categories {
    Fantasia,
    FicçãoCientífica,
    Distopia,
    AçãoEAventura,
    FicçãoPolicial,
    Horror,
    ThrillerESuspense,
    FicçãoHistórica,
    Romance,
    Novela,
    FicçãoFeminina,
    LGBTQ,
    FicçãoContemporânea,
    RealismoMágico,
    GraphicNovel,
    Conto,
    Infantil,
    MemóriasEAutobiografia,
    Biografia,
    Gastronomia,
    ArteEFotografia,
    Autoajuda,
    História,
    Viagem,
    CrimesReais,
    Humor,
    Ensaios,
    Guias,
    ReligiãoEEspiritualidade,
    HumanidadesECiênciasSociais,
    PaternidadeEfamília,
    TecnologiaECiência
}
